apiVersion: v1
kind: ConfigMap
metadata:
  name: web-order-app-config
  namespace: dream-maas
data:
  APP_NAME: "dream-web-order-app"
  JOB_MANAGER_URL: "http://dream-job-manager.dream-maas.svc.cluster.local:8080"
  REQUEST_TIMEOUT_SECONDS: "8"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-order-app
  namespace: dream-maas
  labels:
    app: web-order-app
    component: maas-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-order-app
  template:
    metadata:
      labels:
        app: web-order-app
        component: maas-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: cloudnode
      containers:
        - name: web-order-app
          image: henok28/dream-web-order-app:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: web-order-app-config
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 4
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 4
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-order-app
  namespace: dream-maas
  labels:
    app: web-order-app
spec:
  type: NodePort
  selector:
    app: web-order-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090
