apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudcore-devicestatus-extra
rules:
- apiGroups: ["devices.kubeedge.io"]
  resources: ["devicestatuses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudcore-devicestatus-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudcore-devicestatus-extra
subjects:
- kind: ServiceAccount
  name: cloudcore
  namespace: kubeedge