apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: dht22-sensor1
  namespace: default
spec:
  deviceModelRef:
    name: dht22-model
  nodeName: pigateway
  protocol:
    protocolName: customized
    configData: {}
  properties:
    - name: temperature
      collectCycle: 3000
      reportCycle: 3000
      reportToCloud: true
      visitors:
        protocolName: customized
        configData:
          dataType: string
          metric: temperature
          pin: GPIO4
    - name: humidity
      collectCycle: 3000
      reportCycle: 3000
      reportToCloud: true
      visitors:
        protocolName: customized
        configData:
          dataType: string
          metric: humidity
          pin: GPIO4
---
apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: dht22-sensor2
  namespace: default
spec:
  deviceModelRef:
    name: dht22-model
  nodeName: pigateway
  protocol:
    protocolName: customized
    configData: {}
  properties:
    - name: temperature
      collectCycle: 3000
      reportCycle: 3000
      reportToCloud: true
      visitors:
        protocolName: customized
        configData:
          dataType: string
          metric: temperature
          pin: GPIO17
    - name: humidity
      collectCycle: 3000
      reportCycle: 3000
      reportToCloud: true
      visitors:
        protocolName: customized
        configData:
          dataType: string
          metric: humidity
          pin: GPIO17

# kubectl delete device dht22-sensor1 -n default
# kubectl delete device dht22-sensor2 -n default
# kubectl apply -f dht22-devices.yaml
# kubectl get device dht22-sensor1 -n default -o yaml
# kubectl get device dht22-sensor2 -n default -o yaml