apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceModel
metadata:
  name: dht22-model
  namespace: default
spec:
  protocol: customized
  properties:
    - name: temperature
      description: DHT22 temperature
      type: STRING
      accessMode: ReadOnly
      unit: Celsius
    - name: humidity
      description: DHT22 humidity
      type: STRING
      accessMode: ReadOnly
      unit: Percent

# create the DeviceModel
# kubectl apply -f dht22-devicemodel.yaml